# VOLUMES PARA PERSISTÊNCIA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-local-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
# DEPLOY DO BANCO POSTGRES
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops2023-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db-volume
          persistentVolumeClaim: 
            claimName: db-local-pvc
      containers:
      - name: db
        image: postgres:15.3-alpine3.18
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: dbDevops2023
          - name: POSTGRES_USER
            value: dbUser
          - name: POSTGRES_PASSWORD
            value: db123
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: db-volume
---
# SERVICE PRA COMUNICAÇÃO INTERNA
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432