apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops2023-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:15.3-alpine3.18
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: dbDevops2023
          - name: POSTGRES_USER
            value: dbUser
          - name: POSTGRES_PASSWORD
            value: db123
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
